//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.EmailServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EmailServiceReference.IEmailService")]
    public interface IEmailService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmailService/SendMessage", ReplyAction="http://tempuri.org/IEmailService/SendMessageResponse")]
        void SendMessage(string userName, string password, string sendTo, string title, string body, string[] attachment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmailService/SendMessage", ReplyAction="http://tempuri.org/IEmailService/SendMessageResponse")]
        System.Threading.Tasks.Task SendMessageAsync(string userName, string password, string sendTo, string title, string body, string[] attachment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmailService/ViewMail", ReplyAction="http://tempuri.org/IEmailService/ViewMailResponse")]
        string[] ViewMail(string userName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmailService/ViewMail", ReplyAction="http://tempuri.org/IEmailService/ViewMailResponse")]
        System.Threading.Tasks.Task<string[]> ViewMailAsync(string userName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmailService/DeleteMail", ReplyAction="http://tempuri.org/IEmailService/DeleteMailResponse")]
        void DeleteMail(string userName, string password, int selectedMessage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmailService/DeleteMail", ReplyAction="http://tempuri.org/IEmailService/DeleteMailResponse")]
        System.Threading.Tasks.Task DeleteMailAsync(string userName, string password, int selectedMessage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmailService/ViewMessageBody", ReplyAction="http://tempuri.org/IEmailService/ViewMessageBodyResponse")]
        string ViewMessageBody(string userName, string password, int selectedMessage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmailService/ViewMessageBody", ReplyAction="http://tempuri.org/IEmailService/ViewMessageBodyResponse")]
        System.Threading.Tasks.Task<string> ViewMessageBodyAsync(string userName, string password, int selectedMessage);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEmailServiceChannel : Client.EmailServiceReference.IEmailService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EmailServiceClient : System.ServiceModel.ClientBase<Client.EmailServiceReference.IEmailService>, Client.EmailServiceReference.IEmailService {
        
        public EmailServiceClient() {
        }
        
        public EmailServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EmailServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmailServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmailServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void SendMessage(string userName, string password, string sendTo, string title, string body, string[] attachment) {
            base.Channel.SendMessage(userName, password, sendTo, title, body, attachment);
        }
        
        public System.Threading.Tasks.Task SendMessageAsync(string userName, string password, string sendTo, string title, string body, string[] attachment) {
            return base.Channel.SendMessageAsync(userName, password, sendTo, title, body, attachment);
        }
        
        public string[] ViewMail(string userName, string password) {
            return base.Channel.ViewMail(userName, password);
        }
        
        public System.Threading.Tasks.Task<string[]> ViewMailAsync(string userName, string password) {
            return base.Channel.ViewMailAsync(userName, password);
        }
        
        public void DeleteMail(string userName, string password, int selectedMessage) {
            base.Channel.DeleteMail(userName, password, selectedMessage);
        }
        
        public System.Threading.Tasks.Task DeleteMailAsync(string userName, string password, int selectedMessage) {
            return base.Channel.DeleteMailAsync(userName, password, selectedMessage);
        }
        
        public string ViewMessageBody(string userName, string password, int selectedMessage) {
            return base.Channel.ViewMessageBody(userName, password, selectedMessage);
        }
        
        public System.Threading.Tasks.Task<string> ViewMessageBodyAsync(string userName, string password, int selectedMessage) {
            return base.Channel.ViewMessageBodyAsync(userName, password, selectedMessage);
        }
    }
}
